---
title: SUSA Kaggle Capstone
subtitle: "Part 1: Exploratory Data Analysis and Regression" 
author: "Hosted by and maintained by the [Statistics Undergraduate Students Association (SUSA)](https://susa.berkeley.edu). Originally authored by [Arun Ramamurthy](mailto:contact@arun.run) & [Patrick Chao](mailto:prc@berkeley.edu)."
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
---


```{r, echo = F, message = F, warning = F}
library(tidyverse);library(magrittr);library(ggplot2);library(anytime);library(broom);library(stringr);library(ggfortify);library(GGally);library(gridExtra)

outdir = "~/Desktop/WORKSHOP/C/SUSA/susa-repos/crash-course/Kaggle/GRAPHICS/"
printer = function(filename, w = 16, h = 9) {ggsave(paste0(filename, ".png"), path = outdir, units='in', width = w, height = h, dpi=600, limitsize = F)}
```


```{r}
training_set <- read_csv("~/Desktop/WORKSHOP/C/SUSA/susa-repos/crash-course/Kaggle/DATA/house-prices/train.csv") 
#training_set %>% summarise_all(funs(sum(is.na(.))/nrow(training_set))) %>% gather(Column, Count) %>% arrange(desc(Count)) %>% head(10)
eda_set <- training_set %>% drop_na(-c(PoolQC, MiscFeature, Alley, Fence, FireplaceQu, LotFrontage)) 
#nrow(eda_set)/nrow(training_set)
```

```{r}
corr_plot <- function(df) {
  df %>% cor %>% as.data.frame %>% gather(xVar, Corr) %>% mutate(yVar = rep(names(df), times = length(df))) %>%
    ggplot(aes(xVar, yVar, fill = Corr)) + geom_tile() + scale_fill_distiller(type = "div", palette = 2, limits = c(-1, 1)) +
    labs(x = "X Variable", y = "Y Variable") + theme(axis.text.x = element_text(angle = 90))
}
find_high_corr <- function(df, corr = .6) {
  cor_df <- df %>% cor %>% as.data.frame %>% gather(xVar, Corr) %>% mutate(yVar = rep(names(df), times = length(df))) %>%
    filter(Corr >= corr | Corr <= -corr, Corr != 1) %>% arrange(desc(Corr)) 
  return(c(cor_df$xVar, cor_df$yVar) %>% unique)
}
pairs_plot <- function(df){
  df_x <- rename_all(df, function(str){paste(str, "x", sep = ".")})
  df_y <- rename_all(df, function(str){paste(str, "y", sep = ".")})
  cbind(df_x,df_y) %>%
    gather(xVar, xVal, ends_with("x")) %>% gather(yVar, yVal, ends_with("y")) %>% 
    mutate_at(vars(xVar, yVar), function(str){str_sub(str, 1, nchar(str) - 2)}) %>%
    ggplot(aes(xVal, yVal, col = xVar)) + geom_point() + facet_grid(yVar ~ xVar, scales = "free") + 
    labs(x = "X Variable", y = "Y Variable")
}
density_plots <- function(df) {
  df %>% gather(Variable, Value) %>% 
    ggplot(aes(Value, fill = Variable, col = Variable)) + geom_density() + facet_wrap(~ Variable, scales = "free") + 
    theme(legend.position = "none") + labs(x = "", y = "")
}
```

```{r}
find_high_corr(eda_set %>% select_if(is.numeric)) 
corr_plot(eda_set %>% select_if(is.numeric))

pairs_plot(eda_set %>% select(TotalBsmtSF, `1stFlrSF`))
```

```{r}
density_plots(eda_set %>% select_if(is.numeric))
```

# Final Visualizations
```{r}
outdir = "~/Desktop/WORKSHOP/C/SUSA/susa-repos/crash-course/Kaggle/GRAPHICS/"
printer = function(filename, w = 16, h = 9) {ggsave(paste0(filename, ".png"), path = outdir, units='in', width = w, height = h, dpi=600, limitsize = F)}

eda_set %>% select(OverallQual, find_high_corr(eda_set %>% select_if(is.numeric) %>% select(- SalePrice), corr = .7)) %>%
  `names<-`(make.names(names(.))) %>% 
  mutate(BinaryQuality = if_else(OverallQual >= 7, 1, -1) %>% as.factor) %>% 
  select(- OverallQual) %>%
  ggpairs(lower = list(continuous = "smooth_loess"), 
          axisLabels = "none", switch = "both", labeller = label_wrap_gen(), 
          aes(col = BinaryQuality, alpha = .2))
printer("corr_pairs")

corr_plot(eda_set %>% select(find_high_corr(eda_set %>% select_if(is.numeric) %>% select(- SalePrice), corr = .7))) + 
  theme(legend.position = "bottom") + labs(title = "Correlation Plot of Near-Colinear Features", x ="", y = "")
printer("corr_features")

eda_set %>% select_if(is.numeric) %>% gather(Feature, Value, - SalePrice, - Id) %>%
  ggplot(aes(Value, SalePrice, col = Feature)) + geom_jitter(alpha = .2, col = "black") + geom_smooth(method = "lm", size = 2) + 
  facet_wrap(~ Feature, scales = "free_x") + theme_bw() + theme(legend.position = "none") +
  labs(title = "Relationships between Individual Features and Response Variable", x = "") 
printer("y_pairs")
```

```{r}
pca_plot <- function(df, scale = F) {
  autoplot(prcomp(df, scale = scale), data = df, 
         loadings = TRUE, loadings.colour = 'blue',
         loadings.label = TRUE, loadings.label.size = 3)
}
pca_set <- eda_set %>% select(- SalePrice) %>% select_if(is.numeric) %>% drop_na
pca_plot(pca_set)
eda_pca <- prcomp(pca_set)
summary(eda_pca)
eda_pca %>% extract(c("sdev", "center")) %>% as.data.frame %>% mutate(Feature = rownames(.)) %>% arrange(desc(center)) %>% 
  slice(1:20) %>% 
  pull(Feature) -> important_features
print(important_features)
```

# Kaggle 2

## Featuring Engineering
```{r}
set.seed(101)
data.frame(x = seq(1, 10, .009) %>% extract(1:1000)) %>% mutate(y = x^2 + rnorm(1000, 0, 0.5)) %>% 
  mutate(x^2, x, sqrt(x), log(x),  x^-1, x^-2) %>% gather(Function, x, - y) %>% 
  mutate(Function = factor(Function, levels = c("x^2", "x", "sqrt(x)", "log(x)", "x^-1", "x^-2"))) %>% 
  ggplot(aes(x, y, col = Function)) + geom_point(col = "black", alpha = .5, size = .1) + geom_smooth(method = "lm", se = F, size = 2) +
  facet_wrap(~ Function, ncol = 2, nrow = 3, scales = "free_x")
# printer...
data.frame(x = seq(1, 10, .009) %>% extract(1:1000)) %>% mutate(y = x^2 + rnorm(1000, 0, 5)) %>%
  mutate(`x^2` = x^2) %>% gather(Variable, Value, - y) %>% ggplot(aes(Value, y, col = Variable)) + 
  geom_point() + geom_smooth(col = "black", method = "lm") + 
  facet_wrap(~ Variable, nrow = 1, scales = "free_x")  + labs(x = "", title = "Using x' = x^2 fixes our linear model.") + theme(legend.position = "none")
printer("engineering")

eda_set %>% mutate(`log(PoolArea)` = log(PoolArea)) %>% 
  select(MoSold, PoolArea, `log(PoolArea)`) %>% gather(Variable, Value) %>% 
  mutate(Variable = factor(Variable, levels = c("MoSold", "PoolArea", "log(PoolArea)"))) %>% 
  ggplot(aes(Value, fill = Variable, col = Variable)) + geom_density() + facet_wrap(~ Variable, scales = "free", ncol = 1) + 
  theme(legend.position = "none") + labs(x = "", y = "Density") + 
  labs(title = "Inspecting these density plots, MoSold is a fairly well-spread feature. However, PoolArea is not, and suffers from outliers. We can fix it with log!")
printer("spread")
```

