---
title: Introduction to R
subtitle: "Part 3: Data Visualization and Data Analysis"
author: "Hosted by and maintained by the [Statistics Undergraduate Students Association (SUSA)](https://susa.berkeley.edu). Originally authored by Arun Ramamurthy."
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
---
```{r, echo = F}
knitr::opts_chunk$set(eval = F)
```

# About this Document
This is the associated workbook for the [r3](r3.html) tutorial on data visualization and analysis in R. Unlike the previous workshops, this workbook will not be problem set, but project-focused. After all, graphing is fairly subjective, and a creative process requires time trying various approaches to the same problem. 

Using RStudio, replace each ` > TODO ` with a code chunk that answers the associated problem. Then, run the chunk to verify your answers. Some problems require a non-code answer, so simply replace ` > TODO ` with the correct textual answer.

# Data Visualization with `ggplot2`

## Tips for Data Viusalization

What does "tell a story" mean to you? How can you apply your storytelling skills to data visualization?

> TODO 

Argue for a counter-example usecase for one of the tips listed in this tutorial. When would it actually be a good idea to do the reverse?

> TODO

In the tutorial, I advise that you stay away from double-axis graphs. Why? In what way can a data scientist intentionally mislead with them?

> TODO

## Vocabulary for Data Visualization

Briefly define the following terms in your own words: 
- *geom*  
- *aesthetic*  
- *glyph*  
- *layer*

> TODO

## Abstractions of Data Visualization

Write the general workflow for constructing a ggplot, either with a code recipe, description, or story analogy.

> TODO

## `ggplot2` Basics

## Modeling with `ggplot2`

# Data Analysis

## What is Regression?

## Linear Regression

## Polynomial Regression

## Model Selection with `broom`

# Mini-projects

There are two mini-projects for this tutorial, designed to give you practice with EDA and more advanced model selection. 

## Exploratory Data Analysis

Exploratory Data Analysis (**EDA**) is the process of using summary data and data visualization to get a sense of the underlying structures within your data *before* analysis. It's a fairly creative process, and like most creative processes, the best way to learn how to do EDA effectively is with practice. In this mini-project, you will explore either either the `diamonds` or the `mpg` dataset, noting any unusual relationships or outliers. For tips, review all the functions in [`r3`](r3.html). Feel free to email `contact@arun.run` with any questions or for hints.

## Validation & Elastic Net Regression

Now that you're familiar with graphing with `ggplot2` and model selection with `broom`, try your skills at this fairly advanced graphing exercise with the `mtcars` dataset. You will learn a new type of regression, **elastic net regression**, which has not one but two hyperparameters! You will use function definitions to **grid search** hyperparameters, construct a dataframe of various models for predicting the `mpg` of each car with `broom`, and finally graph your validation process with `ggplot2.` For tips, review all the functions in [`r3`](r3.html). Feel free to email `contact@arun.run` with any questions or for hints.
